description: "Tortugas Consulting, LLC is a small consulting business operating out of North Carolina."
keywords:
  - consulting
  - software
  - development
  - web development
  - PHP
  - Ruby
  - Node.js
  - React

author:
  name: "Matthew M. Keeler"
  email: "projects@tortugas-llc.com"
  phone: "662 GNU-UTIL"
  location: "Raleigh-Durham"

social:
  twitter: "keelerm84"
  github: "keelerm84"

contact:
  email: "projects@tortugas-llc.com"
  phone: "662 GNU-UTIL"
